package com.ktcraft.pvs.service.persistance.util;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGenerateStrategy;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedTimestamp;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTypeConvertedJson;
import com.ktcraft.pvs.service.model.Address;

import java.util.Date;

@DynamoDBTable(tableName = "Test")
public class TestTable {

    @DynamoDBHashKey(attributeName = "organization_id")
    public Long organizationId;

    @DynamoDBAttribute(attributeName = "company_name")
    public String companyName;

    @DynamoDBAttribute(attributeName = "legal_name")
    public String legalName;

    @DynamoDBAttribute(attributeName = "tax_identifier")
    public String taxIdentifier;

    @DynamoDBAttribute(attributeName = "email")
    public String email;

    @DynamoDBAttribute(attributeName = "website")
    public String website;

    @DynamoDBAttribute(attributeName = "business_address")
    @DynamoDBTypeConvertedJson
    public Address businessAddress;

    @DynamoDBAttribute(attributeName = "legal_address")
    @DynamoDBTypeConvertedJson
    public Address legalAddress;

    @DynamoDBAutoGeneratedTimestamp(strategy = DynamoDBAutoGenerateStrategy.CREATE)
    @DynamoDBAttribute(attributeName = "created_at")
    public Date createdAt;

    @DynamoDBAutoGeneratedTimestamp(strategy = DynamoDBAutoGenerateStrategy.ALWAYS)
    @DynamoDBAttribute(attributeName = "updated_at")
    public Date updatedAt;
}
