package com.ktcraft.pvs.service.model;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGenerateStrategy;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedTimestamp;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTypeConvertedJson;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBVersionAttribute;
import com.ktcraft.pvs.service.profile.vo.constants.ProfileValidationStatus;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.util.Date;
import java.util.List;
import java.util.Map;
import java.util.Set;

@Data
@AllArgsConstructor
@NoArgsConstructor
@DynamoDBTable(tableName = "ProfileUpdateRequests")
public class ProfileUpdateRequest {

    @DynamoDBHashKey(attributeName = "organization_id")
    public Long organizationId;

    @DynamoDBAttribute(attributeName = "company_name")
    public String companyName;

    @DynamoDBAttribute(attributeName = "legal_name")
    public String legalName;

    @DynamoDBAttribute(attributeName = "tax_identifier")
    public String taxIdentifier;

    @DynamoDBAttribute(attributeName = "email")
    public String email;

    @DynamoDBAttribute(attributeName = "website")
    public String website;

    @DynamoDBAttribute(attributeName = "business_address")
    @DynamoDBTypeConvertedJson
    public Address businessAddress;

    @DynamoDBAttribute(attributeName = "legal_address")
    @DynamoDBTypeConvertedJson
    public Address legalAddress;

    @DynamoDBAutoGeneratedTimestamp(strategy = DynamoDBAutoGenerateStrategy.CREATE)
    @DynamoDBAttribute(attributeName = "created_at")
    public Date createdAt;

    @DynamoDBAutoGeneratedTimestamp(strategy = DynamoDBAutoGenerateStrategy.ALWAYS)
    @DynamoDBAttribute(attributeName = "updated_at")
    public Date updatedAt;

    @DynamoDBAttribute(attributeName = "validation_status")
    @DynamoDBTypeConvertedJson
    public Map<String, List<Account>> validationStatus;

    @DynamoDBAttribute(attributeName = "status")
    @DynamoDBTypeConvertedJson
    public ProfileValidationStatus status;

    @DynamoDBAttribute(attributeName = "created_by")
    @DynamoDBTypeConvertedJson
    public Account createdBy;

    @DynamoDBVersionAttribute
    public Integer version;

    public ProfileUpdateRequest(Long organizationId) {
        setOrganizationId(organizationId);
    }
}
